apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dpdk
  name: testpmd
  namespace: sriovdp
spec:
  securityContext:
    fsGroup: 1001
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: quay.io/schseba/dpdk:rhel
      imagePullPolicy: Always
      name: dpdk
      resources:
        limits:
          cpu: "2"
          hugepages-2Mi: 1Gi
          memory: 2Gi
          intel.com/intel_sriov_dpdk: 2
        requests:
          cpu: "2"
          hugepages-2Mi: 1Gi
          memory: 2Gi
          intel.com/intel_sriov_dpdk: 2
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
      volumeMounts:
        - mountPath: /mnt/huge
          name: hugepages
  terminationGracePeriodSeconds: 5
  volumes:
    - emptyDir:
        medium: HugePages
      name: hugepages
