apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: rhcos-libreswan
spec:
  osImageURL: quay.io/ykashtan/coreos-9:libreswan
